// All of this was generated by GitHub copilot,
// so I'm not sure how it really works

const convertRGBToHex = (rgb: RGB): string => {
  const { r, g, b } = rgb;
  const hex = ((r << 16) | (g << 8) | b).toString(16);
  return hex.padStart(6, "0");
};

export const convertRGBDecimalToHex = (rgb: RGB): string => {
  const { r, g, b } = rgb;
  const hex = convertRGBToHex({
    r: Math.round(r * 255),
    g: Math.round(g * 255),
    b: Math.round(b * 255),
  });
  return hex;
};
